### ISSUE TITLE
[1.12.2] Advancement obtained

### ISSUE THREAD

**Issue by 016Nojr** [p455w0rd/DankNull#16]
Well... I didnt know /dank/null's could earn advancments, until now...

https://gyazo.com/20dcd2cd428899294302a1f102ed5209

Forge: 14.23.0.2521
/dank/null version: 1.0.10

**Comment by p455w0rd** [comment]
lol..hmm...yeah in the newer (1.11, 1.12.2) versions, I have to use FakePlayers to place the blocks...i'll have to work on a way to disable this..thanks for reporting :)

**Comment by Flanks255** [comment]
whats interesting was i didn't use it to place anything related to summoning the wither.

**Comment by p455w0rd** [comment]
and I don't use advancements...very weird

**Comment by p455w0rd** [comment]
at any rate this should be fixed by https://github.com/MinecraftForge/MinecraftForge/pull/4438 - so using Forge version 14.23.0.2523 or higher should prevent this

**Comment by Flanks255** [comment]
Still happening in 1.2.19 and forge 14.23.1.2556 lol 
[https://cdn.discordapp.com/attachments/231942433015857152/394984774822920193/unknown.png](https://cdn.discordapp.com/attachments/231942433015857152/394984774822920193/unknown.png)

**Comment by p455w0rd** [comment]
nah..just happening again...and it's already fixed by #44
