### ISSUE TITLE
/dank/null deletes items before full

### ISSUE THREAD

**Issue by Xalorous** [p455w0rd/DankNull#222]
This is in Direwolf20 pack.  Currently second tier /dank/null.  I use a TiCon hammer with Silk Touch.  I load stone in, with cobble and diorite, etc.  If I open and look inside, the stone is in the 7th-8th? slot, but the slot appears empty.  If I shiftclick the empty slot one or more times, nothing appears to happen, but if I close the /dank/null, there's ONE stack of stone in my inventory, and the /dank/null does not pick up stone any more.  At this point there should have been 512 stone.

I'm not sure if it's the slot, or if it's stone, or the combination of stone and the slot.

**Comment by Cazadorsniper** [comment]
Does Direwolf20 pack have the latest update?

**Comment by Xalorous** [comment]
I am not sure. Not even sure I have the latest pack version, given the move
from twitch and my having not moved.

**Comment by wlsnbilyb** [comment]
It might be a similar issue to which I had recently where I had ore dictionary enabled on cobblestone by accident, which made it eat all my regular stone as another mod added something that let them share an oredict reference (pretty sure it was tinkers with materialStoneTool)

**Comment by Cazadorsniper** [comment]
Just need to look in the mods folder and curseforge for the mod to figure out if its the latest or not. I believe this has been fixed afaik.

**Comment by BlizzBlu** [comment]
I've manually updated /dank/null to 1.7.89 and p4ssw0rd's library to 2.3.161 - the issue is still occurring. Taking out items or placing them in a /dank/null will get items, seemingly at random, eaten up.
